development:
  mq_uri: "amqp://localhost:5672"
  dissemination:
    source: "dissemination-bifrost-books-dev-queue"
    polling_interval_in_minutes: 1
    polling_interval_in_seconds: 30

test:
  mq_uri: "amqp://localhost:5672"
  dissemination:
      source: "bifrost-ingest-test-queue"
      polling_interval_in_minutes: 1
      polling_interval_in_seconds: 30

production:
  mq_uri: "amqp://sifd-staging-03.kb.dk:5672"
  dissemination:
      source: "bifrost-ingest-prod-queue"
      polling_interval_in_minutes: 1
      polling_interval_in_seconds: 30
